-- Create role and grant account level permissions using ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Create role for Frostlogic application
CREATE ROLE IF NOT EXISTS FROSTLOGIC_ROLE;

-- Grant account level permissions
GRANT EXECUTE TASK ON ACCOUNT TO ROLE FROSTLOGIC_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE FROSTLOGIC_ROLE;

-- Grant role to current user (adjust as needed)
GRANT ROLE FROSTLOGIC_ROLE TO ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS FROSTLOGIC_DB;
GRANT ALL PRIVILEGES ON DATABASE FROSTLOGIC_DB TO ROLE FROSTLOGIC_ROLE;
GRANT OWNERSHIP ON SCHEMA FROSTLOGIC_DB.PUBLIC  TO ROLE FROSTLOGIC_ROLE;

-- Create warehouse for the application
CREATE WAREHOUSE IF NOT EXISTS FROSTLOGIC_WH 
WITH WAREHOUSE_SIZE = 'SMALL'
MAX_CLUSTER_COUNT = 3,
MIN_CLUSTER_COUNT = 1,
SCALING_POLICY = 'STANDARD',
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
COMMENT = 'Warehouse for Frostlogic File Management System';

GRANT ALL PRIVILEGES ON WAREHOUSE FROSTLOGIC_WH TO ROLE FROSTLOGIC_ROLE;